### ISSUE TITLE
diğer ülkelerde çıkan il/ilçeler

### ISSUE THREAD

**Issue by ekremkaraca** [azer/developers-in-turkey#2]
Merhaba,

Ula ilçesi altında görünen sonuçlar aslında Ula'ya ait değil, Filipinler'de bir yer çıkıyor, dikkatinizi çekerim: https://github.com/search?q=location:Ula

**Comment by ogta** [comment]
@azer selam benzer bir durum Sinop üzerinde de var https://github.com/search?q=location:Sinop

**Comment by azer** [comment]
Aramayı Sinop,Turkey olarak değiştirebiliriz ama hem bazı geliştiriciler o sonuçlarda çıkmayacak, hem de şu anda pek zamanım yok scriptleri yeni baştan yürütmek için :)
