### ISSUE TITLE
Being a github user is not essential to being a software developer or vice-versa

### ISSUE THREAD

**Issue by oguzcelik** [azer/developers-in-turkey#4]
Being a github user doesn't show you are a developer nor not being a github user makes you less of a developer. You should fix the readme file to point out that this statistics are for github users not software developers.

 Also on the users list there are organizations, you should use a better filter for search.

**Comment by azer** [comment]
I'd like to add another column to show how many repos are created in that location, this would give more meaningful & accurate insights, got no time though. PRs are welcome 🎉
